<?php 

return [
    'covers'    => ['domicilio','ocurre'],
    'status'    => ['en espera','en ruta','arribo','entregado', 'investigacion realizada'],
    'incidents' => [
        'avisado',
        'carta poder',
        'devolucion',
        'diferencia de peso',
        'en proceso de entrega',
        'extraviada transportadora',
        'generar reporte',
        'por confirmar',
        'reenvio',
        'reporte generado',
        'retener',
        'robo a ruta',
        'saqueo',
        'sin avisar',
        'sin cobertura',
        'sin movimiento',
        'trocada agencia',
        'trocada bodega',
        'trocada transportadora',
        'extraviada potosina',
        'retenida por autoridad',
        'decomiso aduana',
        'pagado gloria',
        'Cobrado',
        'Sin Cobrar',
        'en bodega usa no cruzara',
        'caja no recibida en bodega usa',
        'Diferencia de Medidas',
    ],
];